# -*- coding: utf-8 -*-
"""PROJECT  3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EU1qllsKlliLBEpyVMnm2wqCxA1X4hfB
"""

!mkdir app

!ls

!touch app/main.py app/model.py app/schema.py

!ls
!ls app

!touch requirements.txt Dockerfile README.md sample_request.json

!ls
!ls app

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/model.py
# import pickle
# import numpy as np
# 
# with open("app/model.pkl", "rb") as f:
#     model = pickle.load(f)
# 
# def predict(data):
#     arr = np.array(data).reshape(1, -1)
#     return int(model.predict(arr)[0])

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/schema.py
# from pydantic import BaseModel
# from typing import List
# 
# class InputData(BaseModel):
#     features: List[float]
# 
# class PredictionOutput(BaseModel):
#     prediction: int

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/main.py
# from fastapi import FastAPI
# from app.schema import InputData, PredictionOutput
# from app.model import predict
# 
# app = FastAPI()
# 
# @app.get("/")
# def home():
#     return {"message": "API is running"}
# 
# @app.post("/predict", response_model=PredictionOutput)
# def get_prediction(data: InputData):
#     result = predict(data.features)
#     return {"prediction": result}

from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pickle
import os

os.makedirs("app", exist_ok=True)

X, y = load_iris(return_X_y=True)

model = RandomForestClassifier()
model.fit(X, y)

with open("app/model.pkl", "wb") as f:
    pickle.dump(model, f)

!pip install fastapi uvicorn nest-asyncio pyngrok

!ngrok config add-authtoken 3CoQanSuCxh74ak1hBkrebDP8wf_3kApYQAM11dqhrkg5aLu

import nest_asyncio
from pyngrok import ngrok
import threading
import uvicorn

nest_asyncio.apply()

# Start ngrok
public_url = ngrok.connect(8000)
print(" Public URL:", public_url)

# Run FastAPI in background thread
def run_app():
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000)

thread = threading.Thread(target=run_app)
thread.start()

!ls
!ls app

!zip -r ml-api-project.zip .

from google.colab import files
files.download("ml-api-project.zip")

!cat requirements.txt
